server:
   port: 9091

logging:
  level:
    root: info
    org.springframework.web: "info"
    org.apache.ibatis: "debug"
    org.mybatis: "debug"
  file:
    path: "/springboot/log"

spring:
  datasource:
    username: app_test
    password: AACt79cehg12anfkd
    #url: jdbc:mysql://192.168.0.106:3306/dev
    url: jdbc:mysql://test01-secooC2CDB.master.com:3306/secooC2CDB
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: myspring

management:
  endpoints:
    web:
      exposure:
        include: "*"

person:
  first_name: Mike
  age: 18
  phone: 18888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/
  instance:
    prefer-ip-address: true
#spring:
#  profiles:
#    active: dev
rocketmq:
  name-server: 192.168.0.104:9876
  topic: mytopic1
  producer:
    send-message-timeout: 10000
    group: group-lss